### ISSUE TITLE
belepes nelkul mindenfele hiba

### ISSUE THREAD

**Issue by grinapo** [utopszkij/netpolgar#29]
Ha nem lepek be, mindenfele hibakat kapok belepesre unszolas helyett, [peldaul itt](https://netpolgar.hu/member/store?parent_type=teams&parent=1&rank=member).

```
/var/www/customers/vh-42319/web/home/
ErrorException
Undefined variable: parent 
```

**Comment by utopszkij** [comment]
kösz. dolgozok rajta

**Comment by utopszkij** [comment]
javitva
